CREATE TABLE Address (
ID			INT(6)	NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
streetNumber		INT,
streetName		VARCHAR(255),
city			VARCHAR,
state			VARCHAR		
)

CREATE TABLE Customer (
ID			INT(6)	NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
fName			VARCHAR(50),
lName			VARCHAR(50),
rAddress		INT(6),
bAddress		INT(6),
email			VARCHAR,
FOREIGN KEY(rAddress) REFERENCES Address(ID),
FOREIGN KEY(bAddress) REFERENCES Address(ID)		
)

CREATE TABLE Admin (
ID 			INT(6)	NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
fName			VARCHAR(50),
lName			VARCHAR(50),
email			VARCHAR
)

CREATE TABLE CustomerLogin(
userID			INT(6)	NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
password		VARCHAR,
customerID		INT(6),
FOREIGN KEY(customerID) REFERENCES Customer(ID)
)

CREATE TABLE AdminLogin(
userID			INT(6)	NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
password		VARCHAR,
adminID		INT(6),
FOREIGN KEY(adminID) REFERENCES Admin(ID)
)

CREATE TABLE Item(
userID			INT(6)	NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
size			INT,
price			FLOAT,
type			VARCHAR,
description		VARCHAR,
gender			VARCHAR
)

CREATE TABLE Order(
ID			INT(6)	NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
date			DATE,
subTotal		FLOAT,
customerID		INT(6),
itemID			INT(6),
FOREIGN KEY(customerID) REFERENCES Customer(ID),
FOREIGN KEY(itemID) REFERENCES Item(ID)
)